### ISSUE TITLE
 When to support android-31, if I try to do it myself, do you have any suggestions?

### ISSUE THREAD

**Issue by huakaijian** [DeviceFarmer/minicap#25]
I try to run minicap in android 12 . but not find minicap.so.

**Comment by varundtsfi** [comment]
Right now here we are using apk not minicap.so binaries. As per the new solution .so is not required

**Comment by varundtsfi** [comment]
If you want Minicap.so by yourself then you have to build the android 12 beta 4(current code base) by yourself .
