### ISSUE TITLE
Need android-31 arm64-v8a.so

### ISSUE THREAD

**Issue by bikeebh** [DeviceFarmer/minicap#27]
@pcrepieux
I need minicap31.so for armv8_64 as I am using vnc. I have intergrated vnc with android-31 arm64-v8a
your current apk approach is not suitalble for me can you provide me android-31 arm64-v8a.so 

I will integrate your apk approach later but right now I need minicap.so for android 12 support

**Comment by varundtsfi** [comment]
@pcrepieux You can use android-12.0.0_r1 too. It'ss compiling mostly 96%. I am also trying the same But this time I am using  
**android-12.0.0_r1** . I will keep posted  the results here.

**Comment by varundtsfi** [comment]
Hi @pcrepieux 
I have build the android-12_0.0.r1 successfully with minicap and get the .so file too. But I am getting the following error
CANNOT LINK EXECUTABLE "/data/local/tmp//androidvncserver": cannot locate symbol "**_Z28minicap_try_get_display_infoiPN7Minicap11DisplayInfoE**" referenced by "/data/local/tmp/androidvncserver"...

I am debugging it step by step. @pcrepieux Any suggestion here.

**Comment by varundtsfi** [comment]
Hi @bikeebh 
I am trying but getting the same error. 

There is a changed from Displayid to android::PhysicalDisplayid Which is creating problem. 

@pcrepieux do you have any update on it🤔.

**Comment by varundtsfi** [comment]
@bikeebh  

here you can use the android 12 support from minicap side using shared libs.

https://github.com/varundtsfi/Android12Support_withso/tree/main/aosp/android-31/arm64-v8a
