### ISSUE TITLE
where is minicap.so for android sdk 32?

### ISSUE THREAD

**Issue by hyeongminju** [DeviceFarmer/minicap#38]
i need minicap.so for android sdk 32.
how can i get that file?
plz let me know where is the file(minicap.so)....

**Comment by ouze0525** [comment]
i am also looking for minicap.so for android sdk 32

**Comment by stoefln** [comment]
There is the minicap kotlin version in the "experimental" dir. Take a look at that run script to see how they use minicap kotlin for connecting to devices which are not supported by the standard minicap distribution:
https://github.com/DeviceFarmer/minicap/blob/master/run.sh

**Comment by varundtsfi** [comment]
**And Its working fine with Android 13 Beta-4**

![Screenshot_2022-07-20_07-47-32](https://user-images.githubusercontent.com/16011730/179881843-b3380167-45bb-4646-ab2b-3400c9c2ff16.png)
@stoefln I have a question in my mind. Few people are using vnc. 
[older issue ](https://github.com/openstf/minicap/issues/100
)
How can we use jpeg data (port:minicap) to  vncserver which is written in cpp.  
any guess

**Comment by varundtsfi** [comment]
> i need minicap.so for android sdk 32. how can i get that file? plz let me know where is the file(minicap.so)....
Hi @ouze0525 and @hyeongminju 
you can download the required binaries from here.

https://github.com/varundtsfi/Android-sdk-32-minicap

**Comment by JesseCodeBones** [comment]
I am working on it, still in progress

**Comment by stoefln** [comment]
Why not just use minicap kotlin? 
Is there some known downside?

**Comment by varundtsfi** [comment]
I guess the problem is their structure either they are using vnc or some other utility which is using minicap so that's why people are always asking for minicap.so.

**Comment by varundtsfi** [comment]
> I am working on it, still in progress

It's already shared
https://github.com/varundtsfi/Android-sdk-32-minicap. please take it from here .

**Comment by varundtsfi** [comment]
> Why not just use minicap kotlin? 
> Is there some known downside?

I guess the problem is their architecture/design either they are using vnc or some other utility which is using minicap so that's why people are always asking for minicap.so.

**Comment by UrielCh** [comment]
hi, minicap for android 32 is now integrated in [@u4/adbkit 4.1.4](https://www.npmjs.org/package/@u4/adbkit)

usage sample:
```ts
const adbClient = adb.createClient();
const devices = await adbClient.listDevices();
if (!devices.length) {
  console.error('Need at least one connected android device');
  return;
}
const deviceClient = devices[0].getClient();
const minicap = deviceClient.minicap({});
await minicap.start();
minicap.on('data', (buf: Buffer) => {
    console.log(`rcv image Buffer ${buf.length} from minicap`);
})
```

**Comment by varundtsfi** [comment]
This is also an older issue and now in master branch minicap_32.so files are there
we have pushed the required so files in the following PR

https://github.com/DeviceFarmer/minicap/pull/58
