### ISSUE TITLE
where is minicap.so for android sdk 33?

### ISSUE THREAD

**Issue by Ternado-git** [DeviceFarmer/minicap#40]
i need minicap.so for android sdk 33.
how can i get that file?

**Comment by varundtsfi** [comment]
Hi @Ternado-git 
You have to use minicap-debug.apk approach for now. team is not providing the minicap.so approach from Android 12 and onwards. 
I have tried to build Android 13 R1 AOSP but now able to succeed, Getting error while getting the display. 
int counter =0;
  std::vector<android::PhysicalDisplayId> physicalDisplayIds =  android::SurfaceComposerClient::getPhysicalDisplayIds();
  std::cout <<"Data need to be printed " physicalDisplayIds.size();
  for (auto  m_displayId : physicalDisplayIds) {  
        MCINFO("PHYSICAL DISPLAY IDS %d", counter);
         dpy = android::SurfaceComposerClient::getPhysicalDisplayToken(m_displayId);
        if(!dpy) {
          MCINFO("MINICAP-33 :- could not get display for id:using getPhysicalDisplayToken");
          dpy = android::SurfaceComposerClient::getInternalDisplayToken();
          if(!dpy){
            MCINFO("MINICAP-33 :- could not get display for id:getInternalDisplayToken");
          }else{
            MCINFO("MINICAP-33 :- Able to get the display id:getInternalDisplayToken");
          }
        }else{
          MCINFO("MINICAP-33 :- Able to get the display for id:using getPhysicalDisplayToken");
        }
        counter++;
  }


OR

https://cs.android.com/android/platform/superproject/+/master:frameworks/av/cmds/screenrecord/screenrecord.cpp;drc=d1a53fbe9a58652fa677af9bb1b07612f5c2e0ed;l=1171
here what would be the valude of  :fromValue<PhysicalDisplayId>**(atoll(optarg));**
what would be the argument over here?

**Comment by Ternado-git** [comment]
Thank you for your reply, and where can i get the minicap_debug.apk?

**Comment by varundtsfi** [comment]
Hi @Ternado-git 
You have to run the following script(run.sh with required params) https://github.com/DeviceFarmer/minicap/blob/master/run.sh

This will build the following project and generate the apk and install to inside the device.
 https://github.com/DeviceFarmer/minicap/tree/master/experimental

**Comment by varundtsfi** [comment]
This is the Duplicate issue related with the following https://github.com/DeviceFarmer/minicap/issues/41

We can close this issue. we have pushed the required so files in the following PR

https://github.com/DeviceFarmer/minicap/pull/58
