### ISSUE TITLE
b'CANNOT LINK EXECUTABLE "/data/local/tmp/minicap": cannot locate symbol "_ZTVN7android13LayerMetadataE" referenced by "/data/local/tmp/minicap.so"...\r\n'

### ISSUE THREAD

**Issue by moumde** [DeviceFarmer/minicap#48]
**What is the issue or idea you have?**
I'm trying to adapt minicap on Android U. At present, I have successfully compiled, but the following error is reported in the actual application.
`b'CANNOT LINK EXECUTABLE "/data/local/tmp/minicap": cannot locate symbol "_ZTVN7android13LayerMetadataE" referenced by "/data/local/tmp/minicap.so"...\r\n'`

I don't have a clue how to solve this problem, can anyone provide some help

**Have you tried STF?**

**Comment by JesseCodeBones** [comment]
you are linking android13 lib to android14, so it failed, android 14 is still not started

**Comment by moumde** [comment]
> you are linking android13 lib to android14, so it failed, android 14 is still not started

Well, I finally finished my work. Thanks again for your code.
