### ISSUE TITLE
android.view.SurfaceControl.createDisplay seems to be removed

### ISSUE THREAD

**Issue by qua-iy** [DeviceFarmer/minicap#54]
**What is the issue or idea you have?**

I am testing Android 15 Beta 1 on STF, but minicap seems to be crashed on launch.
From logcat, it says `java.lang.NoSuchMethodException: android.view.SurfaceControl.createDisplay [class java.lang.String, boolean]`, guessing certain internal API is removed from Android [used](https://github.com/DeviceFarmer/minicap/blob/0276fbeff6803c7ff4e39450f7c87a2ba59be25e/experimental/app/src/main/java/io/devicefarmer/minicap/utils/SurfaceControl.kt#L91-L102) inside minicap.
I found that related [issue](https://github.com/Genymobile/scrcpy/issues/4656) at scrcpy, with a [commit](https://github.com/Genymobile/scrcpy/commit/be3f949aa5c4dcad276ac0f2b36671a3309ce12f) to remove usage of same internal API.

I am not familiar with minicap and internal API, could anybody fix this issue?

Here are logs of logcat:

```
04-15 13:43:36.437 13748 13748 E SurfaceControl: SurfaceControl error
04-15 13:43:36.437 13748 13748 E SurfaceControl: java.lang.NoSuchMethodException: android.view.SurfaceControl.createDisplay [class java.lang.String, boolean]
04-15 13:43:36.437 13748 13748 E SurfaceControl: 	at java.lang.Class.getMethod(Class.java:2950)
04-15 13:43:36.437 13748 13748 E SurfaceControl: 	at java.lang.Class.getMethod(Class.java:2450)
04-15 13:43:36.437 13748 13748 E SurfaceControl: 	at io.devicefarmer.minicap.utils.SurfaceControl.createDisplay(SurfaceControl.kt:93)
04-15 13:43:36.437 13748 13748 E SurfaceControl: 	at io.devicefarmer.minicap.provider.SurfaceProvider.initSurface(SurfaceProvider.kt:87)
04-15 13:43:36.437 13748 13748 E SurfaceControl: 	at io.devicefarmer.minicap.provider.SurfaceProvider.initSurface(SurfaceProvider.kt:106)
04-15 13:43:36.437 13748 13748 E SurfaceControl: 	at io.devicefarmer.minicap.provider.SurfaceProvider.onConnection(SurfaceProvider.kt:75)
04-15 13:43:36.437 13748 13748 E SurfaceControl: 	at io.devicefarmer.minicap.SimpleServer.start(SimpleServer.kt:41)
04-15 13:43:36.437 13748 13748 E SurfaceControl: 	at io.devicefarmer.minicap.Main$Companion.main(Main.kt:87)
04-15 13:43:36.437 13748 13748 E SurfaceControl: 	at io.devicefarmer.minicap.Main.main(Unknown Source:2)
04-15 13:43:36.437 13748 13748 E SurfaceControl: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
04-15 13:43:36.437 13748 13748 E SurfaceControl: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
04-15 13:43:36.437 13748 13748 D AndroidRuntime: Shutting down VM
04-15 13:43:36.438 13748 13748 E AndroidRuntime: FATAL EXCEPTION: main
04-15 13:43:36.438 13748 13748 E AndroidRuntime: PID: 13748
04-15 13:43:36.438 13748 13748 E AndroidRuntime: java.lang.Error: java.lang.NoSuchMethodException: android.view.SurfaceControl.createDisplay [class java.lang.String, boolean]
04-15 13:43:36.438 13748 13748 E AndroidRuntime: 	at io.devicefarmer.minicap.utils.SurfaceControl.createDisplay(SurfaceControl.kt:100)
04-15 13:43:36.438 13748 13748 E AndroidRuntime: 	at io.devicefarmer.minicap.provider.SurfaceProvider.initSurface(SurfaceProvider.kt:87)
04-15 13:43:36.438 13748 13748 E AndroidRuntime: 	at io.devicefarmer.minicap.provider.SurfaceProvider.initSurface(SurfaceProvider.kt:106)
04-15 13:43:36.438 13748 13748 E AndroidRuntime: 	at io.devicefarmer.minicap.provider.SurfaceProvider.onConnection(SurfaceProvider.kt:75)
04-15 13:43:36.438 13748 13748 E AndroidRuntime: 	at io.devicefarmer.minicap.SimpleServer.start(SimpleServer.kt:41)
04-15 13:43:36.438 13748 13748 E AndroidRuntime: 	at io.devicefarmer.minicap.Main$Companion.main(Main.kt:87)
04-15 13:43:36.438 13748 13748 E AndroidRuntime: 	at io.devicefarmer.minicap.Main.main(Unknown Source:2)
04-15 13:43:36.438 13748 13748 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
04-15 13:43:36.438 13748 13748 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
04-15 13:43:36.438 13748 13748 E AndroidRuntime: Caused by: java.lang.NoSuchMethodException: android.view.SurfaceControl.createDisplay [class java.lang.String, boolean]
04-15 13:43:36.438 13748 13748 E AndroidRuntime: 	at java.lang.Class.getMethod(Class.java:2950)
04-15 13:43:36.438 13748 13748 E AndroidRuntime: 	at java.lang.Class.getMethod(Class.java:2450)
04-15 13:43:36.438 13748 13748 E AndroidRuntime: 	at io.devicefarmer.minicap.utils.SurfaceControl.createDisplay(SurfaceControl.kt:93)
04-15 13:43:36.438 13748 13748 E AndroidRuntime: 	... 8 more
04-15 13:43:36.438 13748 13748 E AndroidRuntime: Error reporting crash
04-15 13:43:36.438 13748 13748 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
04-15 13:43:36.438 13748 13748 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)
04-15 13:43:36.438 13748 13748 E AndroidRuntime: 	at android.os.BinderProxy.transact(BinderProxy.java:586)
04-15 13:43:36.438 13748 13748 E AndroidRuntime: 	at android.os.IServiceManager$Stub$Proxy.checkService(IServiceManager.java:441)
04-15 13:43:36.438 13748 13748 E AndroidRuntime: 	at android.os.ServiceManagerProxy.getService(ServiceManagerNative.java:63)
04-15 13:43:36.438 13748 13748 E AndroidRuntime: 	at android.os.ServiceManager.rawGetService(ServiceManager.java:428)
04-15 13:43:36.438 13748 13748 E AndroidRuntime: 	at android.os.ServiceManager.getService(ServiceManager.java:175)
04-15 13:43:36.438 13748 13748 E AndroidRuntime: 	at android.app.ActivityManager$3.create(ActivityManager.java:5497)
04-15 13:43:36.438 13748 13748 E AndroidRuntime: 	at android.app.ActivityManager$3.create(ActivityManager.java:5494)
04-15 13:43:36.438 13748 13748 E AndroidRuntime: 	at android.util.Singleton.get(Singleton.java:44)
04-15 13:43:36.438 13748 13748 E AndroidRuntime: 	at android.app.ActivityManager.getService(ActivityManager.java:5485)
04-15 13:43:36.438 13748 13748 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit.java:170)
04-15 13:43:36.438 13748 13748 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1071)
04-15 13:43:36.438 13748 13748 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1066)
04-15 13:43:36.438 13748 13748 E AndroidRuntime: 	at java.lang.Thread.dispatchUncaughtException(Thread.java:2306)
```

**Have you tried STF?**

Of course yes.

**Comment by stoefln** [comment]
Yup, it's not available anymore.
We fixed it in this commit: https://github.com/repeato-qa/minicap/commit/22b1e3fd3fd389397cee60365c3b915dfa00a107

**Comment by KishanDasani** [comment]
@stoefln @koral--  is there any update on this? is it refactored or merged anywhere?

**Comment by KishanDasani** [comment]
> Hi @KishanDasani
> 
> Actually I have the fix but I am very much familiar with Java now trying to add my code and send a PR.
> 
> By this weekend I will send the PR.

Thank you. will be a big help.

**Comment by KishanDasani** [comment]
@varundtsfi 

I have cloned fork of **repeato-qa**, which has fix for this issue, on my mac system and did the build with `ndk-build` after setting up environment as mentioned in readme. (installed ndk, and make)

that gave me 3 files in **libs** folder (minicap, minicap-nopie and minicap.so) for arm64-v8a and armeabi-v7a. and I replaced them directly in my node_modules (only minicap & minicap-nopie) files under **@devicefarmer/minicap-prebuilt/prebuilt/<_ABI_>/bin**

![Screenshot 2024-05-09 at 17 20 18](https://github.com/DeviceFarmer/minicap/assets/50163538/f20d53f6-4011-475a-a687-1bb31d8a89e1)
_image 1: generated files inside libs folder via ndk-build command_

but now because minicap-prebuilt npm package is not having folders for SDK 31, 32, 33, 34 under lib folder, these files are not taking effect as per the code written in lib/units/device/resources/minicap.js.

![Screenshot 2024-05-09 at 17 22 41](https://github.com/DeviceFarmer/minicap/assets/50163538/6d18c5e5-983a-476c-97ce-5a19a36ae551)
_image 2: folders for SDK 31 to 34 is not present_

is it advisable to create folders for these missing SDKs under **@devicefarmer/minicap-prebuilt/prebuilt/<_ABI_>/lib/android-<_SDK_>** and paste the generated .so (image 1) files in there?

**Comment by stoefln** [comment]
@KishanDasani the fix is entirely independent from the native binaries. The native binaries are mostly used for old devices AFAIS. 
You can just open the project (folder "experimental" in project root) via Android Studio, build an apk and that's it.

**Comment by KishanDasani** [comment]
> @KishanDasani the fix is entirely independent from the native binaries. The native binaries are mostly used for old devices AFAIS. You can just open the project (folder "experimental" in project root) via Android Studio, build an apk and that's it.

so directly building an apk from experimental folder and replcing it with apk in "noarc" folder will do the work?

**Comment by stoefln** [comment]
Not sure where the apk needs to go exactly. We are not using minicap as part of stf.

**Comment by KishanDasani** [comment]
I'm using minicap with stf as npm package and facing the issue there itself.

do you suggest to put debug apk, which we'll get by building from experimental folder, into node_modules directly is a good idea? 

I'm in need to fix this issue in production environment though.

**Comment by varundtsfi** [comment]
@KishanDasani  and @stoefln 

Actually minicap no more suppted the .so file instead of they have move to the apk approach for screencasting. 
https://github.com/DeviceFarmer/minicap/issues/50#issuecomment-1749977780

You just wait till this weekend hope i will give you the fix in apk itself as I have the fix

**Comment by KishanDasani** [comment]
> @KishanDasani and @stoefln
> 
> Actually minicap no more suppted the .so file instead of they have move to the apk approach for screencasting. [#50 (comment)](https://github.com/DeviceFarmer/minicap/issues/50#issuecomment-1749977780)
> 
> You just wait till this weekend hope i will give you the fix in apk itself as I have the fix

no issues, @varundtsfi 
as of now, I built debug apk from experimental folder and was able to get my screen running successfully for pixel devices via stf.
but screenshots are broken, even with other devices which are not pixel and running on lower android versions.

**Comment by KishanDasani** [comment]
> > @KishanDasani and @stoefln
> > Actually minicap no more suppted the .so file instead of they have move to the apk approach for screencasting. [#50 (comment)](https://github.com/DeviceFarmer/minicap/issues/50#issuecomment-1749977780)
> > You just wait till this weekend hope i will give you the fix in apk itself as I have the fix
> 
> no issues, @varundtsfi as of now, I built debug apk from experimental folder and was able to get my screen running successfully for pixel devices via stf. but screenshots are broken, even with other devices which are not pixel and running on lower android versions.

Hi, @varundtsfi 
did you get chance to look into this?

**Comment by KishanDasani** [comment]
> Yup, it's not available anymore. We fixed it in this commit (by picking taking changes from scrcpy) : [repeato-qa@22b1e3f](https://github.com/repeato-qa/minicap/commit/22b1e3fd3fd389397cee60365c3b915dfa00a107)
> 
> Sorry, the commit is quite a mess, that's why I didn't send a PR.
> 
> I think we should gradually migrate the minicap code to look more like scrcpy. It's just better maintained, and we would save time fixing stuff if we had the same (or more similar) classes and overall structure.
> 
> The relevant lines are those: [repeato-qa@22b1e3f#diff-30e1d69f804022c9c0b456b1a514bf3a0d8ab601c430c6a7d9ec32f729b1cf0dR144-R178](https://github.com/repeato-qa/minicap/commit/22b1e3fd3fd389397cee60365c3b915dfa00a107#diff-30e1d69f804022c9c0b456b1a514bf3a0d8ab601c430c6a7d9ec32f729b1cf0dR144-R178)

@stoefln while this fixes screen fetching issue for pixel devices, it breaks screenshot for all the devices.
can you please check or help with this?

**Comment by KishanDasani** [comment]
I was able to solve the screenshot issue by not taking changes of Main.kt file (changing System.err.printLn to log.info) and logger.kt file (adding printLn with every function).

**Comment by varundtsfi** [comment]
> > > @KishanDasani and @stoefln
> > > Actually minicap no more suppted the .so file instead of they have move to the apk approach for screencasting. [#50 (comment)](https://github.com/DeviceFarmer/minicap/issues/50#issuecomment-1749977780)
> > > You just wait till this weekend hope i will give you the fix in apk itself as I have the fix
> > 
> > 
> > no issues, @varundtsfi as of now, I built debug apk from experimental folder and was able to get my screen running successfully for pixel devices via stf. but screenshots are broken, even with other devices which are not pixel and running on lower android versions.
> 
> Hi, @varundtsfi did you get chance to look into this?

Hi Yes,
I have merge the code in KT version on minicap apk
I was busy in some confrences and tomorrow also I will be little busy but yes before end of this week. 
I will send a PR Currently I have added the following files which requested by multiple people 
(https://github.com/DeviceFarmer/minicap/pull/58)

Sorry for the delay

**Comment by KishanDasani** [comment]
> > > > @KishanDasani and @stoefln
> > > > Actually minicap no more suppted the .so file instead of they have move to the apk approach for screencasting. [#50 (comment)](https://github.com/DeviceFarmer/minicap/issues/50#issuecomment-1749977780)
> > > > You just wait till this weekend hope i will give you the fix in apk itself as I have the fix
> > > 
> > > 
> > > no issues, @varundtsfi as of now, I built debug apk from experimental folder and was able to get my screen running successfully for pixel devices via stf. but screenshots are broken, even with other devices which are not pixel and running on lower android versions.
> > 
> > 
> > Hi, @varundtsfi did you get chance to look into this?
> 
> Hi Yes, I have merge the code in KT version on minicap apk I was busy in some confrences and tomorrow also I will be little busy but yes before end of this week. I will send a PR Currently I have added the following files which requested by multiple people (#58)
> 
> Sorry for the delay

Thank you, @varundtsfi 
As of now, I am able to use devices in stf with the minicap apk I built as said earlier.
once you push .apk files for these of the SDKs, will try this solution as well.

**Comment by lamadaoudi** [comment]
Hi. Any updates @varundtsfi ?

**Comment by varundtsfi** [comment]
> Hi. Any updates @varundtsfi ?

Hi @lamadaoudi ,

Yes I am just sending the PR it's already done.
![Screenshot from 2024-05-22 20-31-33](https://github.com/DeviceFarmer/minicap/assets/16011730/06a45a10-47d7-4ae4-bbbf-79403409f16e)

**Comment by varundtsfi** [comment]
Hi @stoefln  , @KishanDasani  and @lamadaoudi  
Now we can close this issue as we have verfied the chagnes.
