### ISSUE TITLE
Help for building apk for android SDKs which doesn't support .so files anymore

### ISSUE THREAD

**Issue by KishanDasani** [DeviceFarmer/minicap#55]
I have Google Pixel 14 device. I am using STF. I faced issue in enrolling this device on STF but it was resolved once I updated the APK.

Post that, the screen of this device was not getting fetched due to errors in minicap as given in #54

I followed the [fix](https://github.com/repeato-qa/minicap/commit/22b1e3fd3fd389397cee60365c3b915dfa00a107) in **repeato-qa** fork and built the project via `ndk-build` as given in readme. have explained it in this [comment](https://github.com/DeviceFarmer/minicap/issues/54#issuecomment-2102518757).

if .so files are no more supported for newer android SDKs, can anyone please guide me with how to build minicap apk?

**Comment by KishanDasani** [comment]
I got a response in #54 that we can simply build an apk from experimental folder and possibly I can replace the apk under node_modules/@devicefarmer/minicap-prebuilt/prebuilt/noarch. 

![Screenshot 2024-05-10 at 09 39 09](https://github.com/DeviceFarmer/minicap/assets/50163538/5c5f9ae2-a199-44e1-b59e-76a6940de50a)
_image 1: place of minicap apk under node_modules_

but this will give me a debug apk and I want to use it in my production deployment. is it advisable to use debug apk in prod environment?

**Comment by smokaleksander** [comment]
Would love to see some guide here. I am stuck as well :/

**Comment by KishanDasani** [comment]
> Would love to see some guide here. I am stuck as well :/

you can open the experimental folder in Android Studio, let indexing and gradle sync be done and then simply build apk. you can build debug apk or can use existing creds, if you are using for other projects, to generate release apk as well.

if you are using stf, you can replace this apk inside node_modules (refer to image 1 [here](https://github.com/DeviceFarmer/minicap/issues/55#issuecomment-2103826255)). and just re-enroll your device, changes will take place.
